// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	AccountNo         string
	MerchantNo        string
	CustomerNo        pgtype.Text
	AccountType       string
	AllowOverdraft    bool
	MaxOverdraftLimit int64
	AllowDebitOut     bool
	AllowCreditIn     bool
	AllowTransfer     bool
	BookEnabled       bool
	Balance           int64
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type AccountBook struct {
	BookNo    pgtype.UUID
	AccountNo string
	ExpireAt  pgtype.Date
	Balance   int64
	CreatedAt pgtype.Timestamptz
}

type AccountBookChangeLog struct {
	ChangeID      int64
	TxnNo         pgtype.UUID
	AccountNo     string
	BookNo        pgtype.UUID
	Delta         int64
	BalanceAfter  int64
	ExpireAt      pgtype.Date
	CreatedAt     pgtype.Timestamptz
	BalanceBefore int64
}

type AccountChangeLog struct {
	ChangeID      int64
	TxnNo         pgtype.UUID
	AccountNo     string
	Delta         int64
	BalanceAfter  int64
	CreatedAt     pgtype.Timestamptz
	BalanceBefore int64
}

type CodeSequence struct {
	CodeType  string
	ScopeKey  string
	NextValue int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Customer struct {
	CustomerID       pgtype.UUID
	CustomerNo       string
	MerchantNo       string
	OutUserID        string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DefaultAccountNo pgtype.Text
}

type Merchant struct {
	MerchantID                        pgtype.UUID
	MerchantNo                        string
	Name                              string
	BudgetAccountNo                   string
	ReceivableAccountNo               string
	CreatedAt                         pgtype.Timestamptz
	UpdatedAt                         pgtype.Timestamptz
	AutoCreateAccountOnCustomerCreate bool
	AutoCreateCustomerOnCredit        bool
	WriteoffAccountNo                 pgtype.Text
}

type MerchantApiCredential struct {
	CredentialID     int64
	MerchantNo       string
	SecretCiphertext string
	KeyProvider      string
	KmsKeyID         string
	SecretVersion    int32
	Active           bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type OutboxEvent struct {
	EventID     pgtype.UUID
	TxnNo       pgtype.UUID
	MerchantNo  string
	OutTradeNo  pgtype.Text
	Status      string
	RetryCount  int32
	NextRetryAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ID          int64
}

type Txn struct {
	TxnNo            pgtype.UUID
	MerchantNo       string
	OutTradeNo       string
	BizType          string
	TransferScene    pgtype.Text
	DebitAccountNo   pgtype.Text
	CreditAccountNo  pgtype.Text
	Amount           int64
	Status           string
	RefundOfTxnNo    pgtype.UUID
	RefundableAmount int64
	ErrorCode        pgtype.Text
	ErrorMsg         pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CreditExpireAt   pgtype.Date
	Title            pgtype.Text
	Remark           pgtype.Text
}

type WebhookConfig struct {
	MerchantNo string
	Url        string
	Enabled    bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
