// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchUpdateAccountBookBalances = `-- name: BatchUpdateAccountBookBalances :many
WITH payload AS (
  SELECT
    bn.book_no::uuid AS book_no,
    bl.delta::bigint AS delta
  FROM UNNEST(CAST($1 AS text[])) WITH ORDINALITY AS bn(book_no, ord)
  JOIN UNNEST(CAST($2 AS bigint[])) WITH ORDINALITY AS bl(delta, ord)
    ON bn.ord = bl.ord
)
UPDATE account_book b
SET balance = b.balance + payload.delta
FROM payload
WHERE b.book_no = payload.book_no
RETURNING b.book_no, b.balance
`

type BatchUpdateAccountBookBalancesParams struct {
	BookNos []string
	Deltas  []int64
}

type BatchUpdateAccountBookBalancesRow struct {
	BookNo  pgtype.UUID
	Balance int64
}

func (q *Queries) BatchUpdateAccountBookBalances(ctx context.Context, arg BatchUpdateAccountBookBalancesParams) ([]BatchUpdateAccountBookBalancesRow, error) {
	rows, err := q.db.Query(ctx, batchUpdateAccountBookBalances, arg.BookNos, arg.Deltas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchUpdateAccountBookBalancesRow
	for rows.Next() {
		var i BatchUpdateAccountBookBalancesRow
		if err := rows.Scan(&i.BookNo, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimDueOutboxEvents = `-- name: ClaimDueOutboxEvents :many
WITH picked AS (
  SELECT
    e.id,
    e.created_at
  FROM outbox_event e
  WHERE (
      e.status = 'PENDING'
      AND (e.next_retry_at IS NULL OR e.next_retry_at <= $1::timestamptz)
    ) OR (
      e.status = 'PROCESSING'
      AND e.updated_at <= NOW() - INTERVAL '30 minutes'
    )
  ORDER BY e.created_at ASC, e.id ASC
  LIMIT $2
  FOR UPDATE SKIP LOCKED
),
claimed AS (
  UPDATE outbox_event e
  SET status = 'PROCESSING',
      updated_at = NOW()
  FROM picked p
  WHERE e.id = p.id
  RETURNING
    e.id,
    e.event_id,
    e.txn_no,
    e.merchant_no,
    COALESCE(e.out_trade_no, '') AS out_trade_no,
    e.retry_count,
    p.created_at
)
SELECT
  c.event_id::text AS event_id,
  c.txn_no::text AS txn_no,
  c.merchant_no,
  c.out_trade_no,
  COALESCE(t.biz_type, '') AS biz_type,
  COALESCE(t.transfer_scene, '') AS transfer_scene,
  t.amount,
  COALESCE(t.status, '') AS status,
  c.retry_count
FROM claimed c
JOIN txn t ON t.txn_no = c.txn_no
ORDER BY c.created_at ASC, c.id ASC
`

type ClaimDueOutboxEventsParams struct {
	NowAt     pgtype.Timestamptz
	PageLimit int32
}

type ClaimDueOutboxEventsRow struct {
	EventID       string
	TxnNo         string
	MerchantNo    string
	OutTradeNo    string
	BizType       string
	TransferScene string
	Amount        int64
	Status        string
	RetryCount    int32
}

func (q *Queries) ClaimDueOutboxEvents(ctx context.Context, arg ClaimDueOutboxEventsParams) ([]ClaimDueOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, claimDueOutboxEvents, arg.NowAt, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDueOutboxEventsRow
	for rows.Next() {
		var i ClaimDueOutboxEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.TxnNo,
			&i.MerchantNo,
			&i.OutTradeNo,
			&i.BizType,
			&i.TransferScene,
			&i.Amount,
			&i.Status,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimDueOutboxEventsByTxnNo = `-- name: ClaimDueOutboxEventsByTxnNo :many
WITH picked AS (
  SELECT
    e.id,
    e.created_at
  FROM outbox_event e
  WHERE e.txn_no = NULLIF($1, '')::uuid
    AND (
      (
        e.status = 'PENDING'
        AND (e.next_retry_at IS NULL OR e.next_retry_at <= $2::timestamptz)
      ) OR (
        e.status = 'PROCESSING'
        AND e.updated_at <= NOW() - INTERVAL '30 minutes'
      )
    )
  ORDER BY e.created_at ASC, e.id ASC
  LIMIT $3
  FOR UPDATE SKIP LOCKED
),
claimed AS (
  UPDATE outbox_event e
  SET status = 'PROCESSING',
      updated_at = NOW()
  FROM picked p
  WHERE e.id = p.id
  RETURNING
    e.id,
    e.event_id,
    e.txn_no,
    e.merchant_no,
    COALESCE(e.out_trade_no, '') AS out_trade_no,
    e.retry_count,
    p.created_at
)
SELECT
  c.event_id::text AS event_id,
  c.txn_no::text AS txn_no,
  c.merchant_no,
  c.out_trade_no,
  COALESCE(t.biz_type, '') AS biz_type,
  COALESCE(t.transfer_scene, '') AS transfer_scene,
  t.amount,
  COALESCE(t.status, '') AS status,
  c.retry_count
FROM claimed c
JOIN txn t ON t.txn_no = c.txn_no
ORDER BY c.created_at ASC, c.id ASC
`

type ClaimDueOutboxEventsByTxnNoParams struct {
	TxnNo     interface{}
	NowAt     pgtype.Timestamptz
	PageLimit int32
}

type ClaimDueOutboxEventsByTxnNoRow struct {
	EventID       string
	TxnNo         string
	MerchantNo    string
	OutTradeNo    string
	BizType       string
	TransferScene string
	Amount        int64
	Status        string
	RetryCount    int32
}

func (q *Queries) ClaimDueOutboxEventsByTxnNo(ctx context.Context, arg ClaimDueOutboxEventsByTxnNoParams) ([]ClaimDueOutboxEventsByTxnNoRow, error) {
	rows, err := q.db.Query(ctx, claimDueOutboxEventsByTxnNo, arg.TxnNo, arg.NowAt, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDueOutboxEventsByTxnNoRow
	for rows.Next() {
		var i ClaimDueOutboxEventsByTxnNoRow
		if err := rows.Scan(
			&i.EventID,
			&i.TxnNo,
			&i.MerchantNo,
			&i.OutTradeNo,
			&i.BizType,
			&i.TransferScene,
			&i.Amount,
			&i.Status,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAccount = `-- name: CreateAccount :exec
INSERT INTO account (
  account_no, merchant_no, customer_no, account_type,
  allow_overdraft, max_overdraft_limit,
  allow_debit_out, allow_credit_in, allow_transfer,
  book_enabled, balance
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  0
)
`

type CreateAccountParams struct {
	AccountNo         string
	MerchantNo        string
	CustomerNo        pgtype.Text
	AccountType       string
	AllowOverdraft    bool
	MaxOverdraftLimit int64
	AllowDebitOut     bool
	AllowCreditIn     bool
	AllowTransfer     bool
	BookEnabled       bool
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount,
		arg.AccountNo,
		arg.MerchantNo,
		arg.CustomerNo,
		arg.AccountType,
		arg.AllowOverdraft,
		arg.MaxOverdraftLimit,
		arg.AllowDebitOut,
		arg.AllowCreditIn,
		arg.AllowTransfer,
		arg.BookEnabled,
	)
	return err
}

const createCustomer = `-- name: CreateCustomer :exec
INSERT INTO customer (customer_id, customer_no, merchant_no, out_user_id, default_account_no)
VALUES (
  $1::uuid,
  $2,
  $3,
  $4,
  $5
)
`

type CreateCustomerParams struct {
	CustomerID       pgtype.UUID
	CustomerNo       string
	MerchantNo       string
	OutUserID        string
	DefaultAccountNo pgtype.Text
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) error {
	_, err := q.db.Exec(ctx, createCustomer,
		arg.CustomerID,
		arg.CustomerNo,
		arg.MerchantNo,
		arg.OutUserID,
		arg.DefaultAccountNo,
	)
	return err
}

const createMerchant = `-- name: CreateMerchant :exec
INSERT INTO merchant (
  merchant_id, merchant_no, name, budget_account_no, receivable_account_no
) VALUES (
  $1::uuid,
  $2,
  $3,
  $4,
  $5
)
`

type CreateMerchantParams struct {
	MerchantID          pgtype.UUID
	MerchantNo          string
	Name                string
	BudgetAccountNo     string
	ReceivableAccountNo string
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) error {
	_, err := q.db.Exec(ctx, createMerchant,
		arg.MerchantID,
		arg.MerchantNo,
		arg.Name,
		arg.BudgetAccountNo,
		arg.ReceivableAccountNo,
	)
	return err
}

const createTransferTxn = `-- name: CreateTransferTxn :exec
INSERT INTO txn (
  txn_no, merchant_no, out_trade_no, biz_type, transfer_scene,
  title, remark, debit_account_no, credit_account_no, credit_expire_at, amount, status,
  refund_of_txn_no, refundable_amount, error_code, error_msg
) VALUES (
  NULLIF($1, '')::uuid,
  $2,
  $3,
  $4,
  NULLIF($5, ''),
  NULLIF($6, ''),
  NULLIF($7, ''),
  NULLIF($8, ''),
  NULLIF($9, ''),
  $10::date,
  $11,
  $12,
  NULLIF($13, '')::uuid,
  $14,
  NULLIF($15, ''),
  NULLIF($16, '')
)
`

type CreateTransferTxnParams struct {
	TxnNo            interface{}
	MerchantNo       string
	OutTradeNo       string
	BizType          string
	TransferScene    interface{}
	Title            interface{}
	Remark           interface{}
	DebitAccountNo   interface{}
	CreditAccountNo  interface{}
	CreditExpireAt   pgtype.Date
	Amount           int64
	Status           string
	RefundOfTxnNo    interface{}
	RefundableAmount int64
	ErrorCode        interface{}
	ErrorMsg         interface{}
}

func (q *Queries) CreateTransferTxn(ctx context.Context, arg CreateTransferTxnParams) error {
	_, err := q.db.Exec(ctx, createTransferTxn,
		arg.TxnNo,
		arg.MerchantNo,
		arg.OutTradeNo,
		arg.BizType,
		arg.TransferScene,
		arg.Title,
		arg.Remark,
		arg.DebitAccountNo,
		arg.CreditAccountNo,
		arg.CreditExpireAt,
		arg.Amount,
		arg.Status,
		arg.RefundOfTxnNo,
		arg.RefundableAmount,
		arg.ErrorCode,
		arg.ErrorMsg,
	)
	return err
}

const deactivateActiveMerchantSecrets = `-- name: DeactivateActiveMerchantSecrets :exec
UPDATE merchant_api_credential
SET active = false,
    updated_at = NOW()
WHERE merchant_no = $1
  AND active = true
`

func (q *Queries) DeactivateActiveMerchantSecrets(ctx context.Context, merchantNo string) error {
	_, err := q.db.Exec(ctx, deactivateActiveMerchantSecrets, merchantNo)
	return err
}

const decreaseOriginTxnRefundableIfValid = `-- name: DecreaseOriginTxnRefundableIfValid :one
UPDATE txn
SET refundable_amount = refundable_amount - $1,
    updated_at = NOW()
WHERE txn_no = $2
  AND merchant_no = $3
  AND biz_type = 'TRANSFER'
  AND status = 'RECV_SUCCESS'
  AND refundable_amount >= $1
RETURNING
  COALESCE(debit_account_no, '') AS debit_account_no,
  COALESCE(credit_account_no, '') AS credit_account_no,
  refundable_amount
`

type DecreaseOriginTxnRefundableIfValidParams struct {
	Amount      int64
	OriginTxnNo pgtype.UUID
	MerchantNo  string
}

type DecreaseOriginTxnRefundableIfValidRow struct {
	DebitAccountNo   string
	CreditAccountNo  string
	RefundableAmount int64
}

func (q *Queries) DecreaseOriginTxnRefundableIfValid(ctx context.Context, arg DecreaseOriginTxnRefundableIfValidParams) (DecreaseOriginTxnRefundableIfValidRow, error) {
	row := q.db.QueryRow(ctx, decreaseOriginTxnRefundableIfValid, arg.Amount, arg.OriginTxnNo, arg.MerchantNo)
	var i DecreaseOriginTxnRefundableIfValidRow
	err := row.Scan(&i.DebitAccountNo, &i.CreditAccountNo, &i.RefundableAmount)
	return i, err
}

const getAccountBookForUpdateByAccountExpire = `-- name: GetAccountBookForUpdateByAccountExpire :one
SELECT
  b.book_no,
  b.account_no,
  b.expire_at,
  b.balance
FROM account_book b
WHERE b.account_no = $1
  AND b.expire_at = $2::date
FOR UPDATE OF b
LIMIT 1
`

type GetAccountBookForUpdateByAccountExpireParams struct {
	AccountNo string
	ExpireAt  pgtype.Date
}

type GetAccountBookForUpdateByAccountExpireRow struct {
	BookNo    pgtype.UUID
	AccountNo string
	ExpireAt  pgtype.Date
	Balance   int64
}

func (q *Queries) GetAccountBookForUpdateByAccountExpire(ctx context.Context, arg GetAccountBookForUpdateByAccountExpireParams) (GetAccountBookForUpdateByAccountExpireRow, error) {
	row := q.db.QueryRow(ctx, getAccountBookForUpdateByAccountExpire, arg.AccountNo, arg.ExpireAt)
	var i GetAccountBookForUpdateByAccountExpireRow
	err := row.Scan(
		&i.BookNo,
		&i.AccountNo,
		&i.ExpireAt,
		&i.Balance,
	)
	return i, err
}

const getAccountByMerchantOutUserID = `-- name: GetAccountByMerchantOutUserID :one
SELECT
  a.account_no,
  a.merchant_no,
  COALESCE(a.customer_no, '') AS customer_no,
  a.account_type,
  a.allow_overdraft,
  a.max_overdraft_limit,
  a.allow_debit_out,
  a.allow_credit_in,
  a.allow_transfer,
  a.book_enabled,
  a.balance
FROM account a
JOIN customer c
  ON c.customer_no = a.customer_no
 AND c.merchant_no = a.merchant_no
WHERE c.merchant_no = $1
  AND c.out_user_id = $2
  AND c.default_account_no = a.account_no
LIMIT 1
`

type GetAccountByMerchantOutUserIDParams struct {
	MerchantNo string
	OutUserID  string
}

type GetAccountByMerchantOutUserIDRow struct {
	AccountNo         string
	MerchantNo        string
	CustomerNo        string
	AccountType       string
	AllowOverdraft    bool
	MaxOverdraftLimit int64
	AllowDebitOut     bool
	AllowCreditIn     bool
	AllowTransfer     bool
	BookEnabled       bool
	Balance           int64
}

func (q *Queries) GetAccountByMerchantOutUserID(ctx context.Context, arg GetAccountByMerchantOutUserIDParams) (GetAccountByMerchantOutUserIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByMerchantOutUserID, arg.MerchantNo, arg.OutUserID)
	var i GetAccountByMerchantOutUserIDRow
	err := row.Scan(
		&i.AccountNo,
		&i.MerchantNo,
		&i.CustomerNo,
		&i.AccountType,
		&i.AllowOverdraft,
		&i.MaxOverdraftLimit,
		&i.AllowDebitOut,
		&i.AllowCreditIn,
		&i.AllowTransfer,
		&i.BookEnabled,
		&i.Balance,
	)
	return i, err
}

const getAccountByNo = `-- name: GetAccountByNo :one
SELECT
  a.account_no,
  a.merchant_no,
  COALESCE(a.customer_no, '') AS customer_no,
  a.account_type,
  a.allow_overdraft,
  a.max_overdraft_limit,
  a.allow_debit_out,
  a.allow_credit_in,
  a.allow_transfer,
  a.book_enabled,
  a.balance
FROM account a
WHERE a.account_no = $1
LIMIT 1
`

type GetAccountByNoRow struct {
	AccountNo         string
	MerchantNo        string
	CustomerNo        string
	AccountType       string
	AllowOverdraft    bool
	MaxOverdraftLimit int64
	AllowDebitOut     bool
	AllowCreditIn     bool
	AllowTransfer     bool
	BookEnabled       bool
	Balance           int64
}

func (q *Queries) GetAccountByNo(ctx context.Context, accountNo string) (GetAccountByNoRow, error) {
	row := q.db.QueryRow(ctx, getAccountByNo, accountNo)
	var i GetAccountByNoRow
	err := row.Scan(
		&i.AccountNo,
		&i.MerchantNo,
		&i.CustomerNo,
		&i.AccountType,
		&i.AllowOverdraft,
		&i.MaxOverdraftLimit,
		&i.AllowDebitOut,
		&i.AllowCreditIn,
		&i.AllowTransfer,
		&i.BookEnabled,
		&i.Balance,
	)
	return i, err
}

const getAccountForUpdateByNo = `-- name: GetAccountForUpdateByNo :one
SELECT
  a.account_no,
  a.merchant_no,
  COALESCE(a.customer_no, '') AS customer_no,
  a.account_type,
  a.allow_overdraft,
  a.max_overdraft_limit,
  a.allow_debit_out,
  a.allow_credit_in,
  a.allow_transfer,
  a.book_enabled,
  a.balance
FROM account a
WHERE a.account_no = $1
FOR UPDATE OF a
LIMIT 1
`

type GetAccountForUpdateByNoRow struct {
	AccountNo         string
	MerchantNo        string
	CustomerNo        string
	AccountType       string
	AllowOverdraft    bool
	MaxOverdraftLimit int64
	AllowDebitOut     bool
	AllowCreditIn     bool
	AllowTransfer     bool
	BookEnabled       bool
	Balance           int64
}

func (q *Queries) GetAccountForUpdateByNo(ctx context.Context, accountNo string) (GetAccountForUpdateByNoRow, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdateByNo, accountNo)
	var i GetAccountForUpdateByNoRow
	err := row.Scan(
		&i.AccountNo,
		&i.MerchantNo,
		&i.CustomerNo,
		&i.AccountType,
		&i.AllowOverdraft,
		&i.MaxOverdraftLimit,
		&i.AllowDebitOut,
		&i.AllowCreditIn,
		&i.AllowTransfer,
		&i.BookEnabled,
		&i.Balance,
	)
	return i, err
}

const getAccountNoByCustomerNo = `-- name: GetAccountNoByCustomerNo :one
SELECT c.default_account_no
FROM customer c
WHERE c.merchant_no = $1
  AND c.customer_no = $2
  AND c.default_account_no IS NOT NULL
LIMIT 1
`

type GetAccountNoByCustomerNoParams struct {
	MerchantNo string
	CustomerNo string
}

func (q *Queries) GetAccountNoByCustomerNo(ctx context.Context, arg GetAccountNoByCustomerNoParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getAccountNoByCustomerNo, arg.MerchantNo, arg.CustomerNo)
	var default_account_no pgtype.Text
	err := row.Scan(&default_account_no)
	return default_account_no, err
}

const getActiveSecretCiphertext = `-- name: GetActiveSecretCiphertext :one
SELECT secret_ciphertext
FROM merchant_api_credential
WHERE merchant_no = $1
  AND active = true
ORDER BY secret_version DESC
LIMIT 1
`

func (q *Queries) GetActiveSecretCiphertext(ctx context.Context, merchantNo string) (string, error) {
	row := q.db.QueryRow(ctx, getActiveSecretCiphertext, merchantNo)
	var secret_ciphertext string
	err := row.Scan(&secret_ciphertext)
	return secret_ciphertext, err
}

const getCustomerByOutUserID = `-- name: GetCustomerByOutUserID :one
SELECT
  c.customer_id::text AS customer_id,
  c.customer_no,
  c.merchant_no,
  c.out_user_id,
  COALESCE(c.default_account_no, '') AS default_account_no
FROM customer c
WHERE c.merchant_no = $1
  AND c.out_user_id = $2
LIMIT 1
`

type GetCustomerByOutUserIDParams struct {
	MerchantNo string
	OutUserID  string
}

type GetCustomerByOutUserIDRow struct {
	CustomerID       string
	CustomerNo       string
	MerchantNo       string
	OutUserID        string
	DefaultAccountNo string
}

func (q *Queries) GetCustomerByOutUserID(ctx context.Context, arg GetCustomerByOutUserIDParams) (GetCustomerByOutUserIDRow, error) {
	row := q.db.QueryRow(ctx, getCustomerByOutUserID, arg.MerchantNo, arg.OutUserID)
	var i GetCustomerByOutUserIDRow
	err := row.Scan(
		&i.CustomerID,
		&i.CustomerNo,
		&i.MerchantNo,
		&i.OutUserID,
		&i.DefaultAccountNo,
	)
	return i, err
}

const getMaxSecretVersion = `-- name: GetMaxSecretVersion :one
SELECT COALESCE(MAX(secret_version), 0)::int AS max_secret_version
FROM merchant_api_credential
WHERE merchant_no = $1
`

func (q *Queries) GetMaxSecretVersion(ctx context.Context, merchantNo string) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxSecretVersion, merchantNo)
	var max_secret_version int32
	err := row.Scan(&max_secret_version)
	return max_secret_version, err
}

const getMerchantByNo = `-- name: GetMerchantByNo :one
SELECT merchant_id::text, merchant_no, name, budget_account_no, receivable_account_no
FROM merchant
WHERE merchant_no = $1
LIMIT 1
`

type GetMerchantByNoRow struct {
	MerchantID          string
	MerchantNo          string
	Name                string
	BudgetAccountNo     string
	ReceivableAccountNo string
}

func (q *Queries) GetMerchantByNo(ctx context.Context, merchantNo string) (GetMerchantByNoRow, error) {
	row := q.db.QueryRow(ctx, getMerchantByNo, merchantNo)
	var i GetMerchantByNoRow
	err := row.Scan(
		&i.MerchantID,
		&i.MerchantNo,
		&i.Name,
		&i.BudgetAccountNo,
		&i.ReceivableAccountNo,
	)
	return i, err
}

const getRefundDebitStatsByOrigin = `-- name: GetRefundDebitStatsByOrigin :one
SELECT
  COALESCE(SUM(t.amount), 0)::bigint AS total_debited,
  COALESCE(SUM(CASE WHEN t.txn_no = $1::uuid THEN t.amount ELSE 0 END), 0)::bigint AS current_debited
FROM txn t
JOIN account_change_log acl
  ON acl.txn_no = t.txn_no
WHERE t.merchant_no = $2
  AND t.refund_of_txn_no = $3::uuid
  AND t.biz_type = 'REFUND'
  AND acl.account_no = $4
  AND acl.delta < 0
`

type GetRefundDebitStatsByOriginParams struct {
	RefundTxnNo           pgtype.UUID
	MerchantNo            string
	OriginTxnNo           pgtype.UUID
	OriginCreditAccountNo string
}

type GetRefundDebitStatsByOriginRow struct {
	TotalDebited   int64
	CurrentDebited int64
}

func (q *Queries) GetRefundDebitStatsByOrigin(ctx context.Context, arg GetRefundDebitStatsByOriginParams) (GetRefundDebitStatsByOriginRow, error) {
	row := q.db.QueryRow(ctx, getRefundDebitStatsByOrigin,
		arg.RefundTxnNo,
		arg.MerchantNo,
		arg.OriginTxnNo,
		arg.OriginCreditAccountNo,
	)
	var i GetRefundDebitStatsByOriginRow
	err := row.Scan(&i.TotalDebited, &i.CurrentDebited)
	return i, err
}

const getTransferTxnByNo = `-- name: GetTransferTxnByNo :one
SELECT
  t.txn_no::text AS txn_no,
  t.merchant_no,
  t.out_trade_no,
  COALESCE(t.title, '') AS title,
  COALESCE(t.remark, '') AS remark,
  COALESCE(t.biz_type, '') AS biz_type,
  COALESCE(t.transfer_scene, '') AS transfer_scene,
  COALESCE(t.debit_account_no, '') AS debit_account_no,
  COALESCE(t.credit_account_no, '') AS credit_account_no,
  t.credit_expire_at,
  t.amount,
  COALESCE(t.refund_of_txn_no::text, '')::text AS refund_of_txn_no,
  t.refundable_amount,
  COALESCE(t.status, '') AS status,
  COALESCE(t.error_code, '') AS error_code,
  COALESCE(t.error_msg, '') AS error_msg,
  t.created_at
FROM txn t
WHERE t.txn_no = NULLIF($1, '')::uuid
LIMIT 1
`

type GetTransferTxnByNoRow struct {
	TxnNo            string
	MerchantNo       string
	OutTradeNo       string
	Title            string
	Remark           string
	BizType          string
	TransferScene    string
	DebitAccountNo   string
	CreditAccountNo  string
	CreditExpireAt   pgtype.Date
	Amount           int64
	RefundOfTxnNo    string
	RefundableAmount int64
	Status           string
	ErrorCode        string
	ErrorMsg         string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetTransferTxnByNo(ctx context.Context, txnNo interface{}) (GetTransferTxnByNoRow, error) {
	row := q.db.QueryRow(ctx, getTransferTxnByNo, txnNo)
	var i GetTransferTxnByNoRow
	err := row.Scan(
		&i.TxnNo,
		&i.MerchantNo,
		&i.OutTradeNo,
		&i.Title,
		&i.Remark,
		&i.BizType,
		&i.TransferScene,
		&i.DebitAccountNo,
		&i.CreditAccountNo,
		&i.CreditExpireAt,
		&i.Amount,
		&i.RefundOfTxnNo,
		&i.RefundableAmount,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMsg,
		&i.CreatedAt,
	)
	return i, err
}

const getTransferTxnByOutTradeNo = `-- name: GetTransferTxnByOutTradeNo :one
SELECT
  t.txn_no::text AS txn_no,
  t.merchant_no,
  t.out_trade_no,
  COALESCE(t.title, '') AS title,
  COALESCE(t.remark, '') AS remark,
  COALESCE(t.biz_type, '') AS biz_type,
  COALESCE(t.transfer_scene, '') AS transfer_scene,
  COALESCE(t.debit_account_no, '') AS debit_account_no,
  COALESCE(t.credit_account_no, '') AS credit_account_no,
  t.credit_expire_at,
  t.amount,
  COALESCE(t.refund_of_txn_no::text, '')::text AS refund_of_txn_no,
  t.refundable_amount,
  COALESCE(t.status, '') AS status,
  COALESCE(t.error_code, '') AS error_code,
  COALESCE(t.error_msg, '') AS error_msg,
  t.created_at
FROM txn t
WHERE t.merchant_no = $1
  AND t.out_trade_no = $2
LIMIT 1
`

type GetTransferTxnByOutTradeNoParams struct {
	MerchantNo string
	OutTradeNo string
}

type GetTransferTxnByOutTradeNoRow struct {
	TxnNo            string
	MerchantNo       string
	OutTradeNo       string
	Title            string
	Remark           string
	BizType          string
	TransferScene    string
	DebitAccountNo   string
	CreditAccountNo  string
	CreditExpireAt   pgtype.Date
	Amount           int64
	RefundOfTxnNo    string
	RefundableAmount int64
	Status           string
	ErrorCode        string
	ErrorMsg         string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetTransferTxnByOutTradeNo(ctx context.Context, arg GetTransferTxnByOutTradeNoParams) (GetTransferTxnByOutTradeNoRow, error) {
	row := q.db.QueryRow(ctx, getTransferTxnByOutTradeNo, arg.MerchantNo, arg.OutTradeNo)
	var i GetTransferTxnByOutTradeNoRow
	err := row.Scan(
		&i.TxnNo,
		&i.MerchantNo,
		&i.OutTradeNo,
		&i.Title,
		&i.Remark,
		&i.BizType,
		&i.TransferScene,
		&i.DebitAccountNo,
		&i.CreditAccountNo,
		&i.CreditExpireAt,
		&i.Amount,
		&i.RefundOfTxnNo,
		&i.RefundableAmount,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMsg,
		&i.CreatedAt,
	)
	return i, err
}

const getTransferTxnStageForUpdate = `-- name: GetTransferTxnStageForUpdate :one
SELECT
  t.txn_no,
  COALESCE(t.status, '') AS status,
  COALESCE(t.debit_account_no, '') AS debit_account_no,
  COALESCE(t.credit_account_no, '') AS credit_account_no,
  t.credit_expire_at,
  t.amount,
  t.merchant_no,
  t.out_trade_no,
  COALESCE(t.biz_type, '') AS biz_type,
  COALESCE(t.transfer_scene, '') AS transfer_scene,
  t.refund_of_txn_no
FROM txn t
WHERE t.txn_no = NULLIF($1, '')::uuid
FOR UPDATE
LIMIT 1
`

type GetTransferTxnStageForUpdateRow struct {
	TxnNo           pgtype.UUID
	Status          string
	DebitAccountNo  string
	CreditAccountNo string
	CreditExpireAt  pgtype.Date
	Amount          int64
	MerchantNo      string
	OutTradeNo      string
	BizType         string
	TransferScene   string
	RefundOfTxnNo   pgtype.UUID
}

func (q *Queries) GetTransferTxnStageForUpdate(ctx context.Context, txnNo interface{}) (GetTransferTxnStageForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getTransferTxnStageForUpdate, txnNo)
	var i GetTransferTxnStageForUpdateRow
	err := row.Scan(
		&i.TxnNo,
		&i.Status,
		&i.DebitAccountNo,
		&i.CreditAccountNo,
		&i.CreditExpireAt,
		&i.Amount,
		&i.MerchantNo,
		&i.OutTradeNo,
		&i.BizType,
		&i.TransferScene,
		&i.RefundOfTxnNo,
	)
	return i, err
}

const getWebhookConfig = `-- name: GetWebhookConfig :one
SELECT merchant_no, url, enabled, created_at, updated_at
FROM webhook_config
WHERE merchant_no = $1
LIMIT 1
`

func (q *Queries) GetWebhookConfig(ctx context.Context, merchantNo string) (WebhookConfig, error) {
	row := q.db.QueryRow(ctx, getWebhookConfig, merchantNo)
	var i WebhookConfig
	err := row.Scan(
		&i.MerchantNo,
		&i.Url,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const initCodeSequence = `-- name: InitCodeSequence :exec
INSERT INTO code_sequence (code_type, scope_key, next_value)
VALUES (
  $1,
  $2,
  0
)
ON CONFLICT (code_type, scope_key)
DO NOTHING
`

type InitCodeSequenceParams struct {
	CodeType string
	ScopeKey string
}

func (q *Queries) InitCodeSequence(ctx context.Context, arg InitCodeSequenceParams) error {
	_, err := q.db.Exec(ctx, initCodeSequence, arg.CodeType, arg.ScopeKey)
	return err
}

const insertAccountBookChange = `-- name: InsertAccountBookChange :exec
INSERT INTO account_book_change_log (txn_no, account_no, book_no, delta, balance_before, balance_after, expire_at)
VALUES (
  $1::uuid,
  $2,
  $3::uuid,
  $4,
  $5,
  $6,
  $7::date
)
`

type InsertAccountBookChangeParams struct {
	TxnNo         pgtype.UUID
	AccountNo     string
	BookNo        pgtype.UUID
	Delta         int64
	BalanceBefore int64
	BalanceAfter  int64
	ExpireAt      pgtype.Date
}

func (q *Queries) InsertAccountBookChange(ctx context.Context, arg InsertAccountBookChangeParams) error {
	_, err := q.db.Exec(ctx, insertAccountBookChange,
		arg.TxnNo,
		arg.AccountNo,
		arg.BookNo,
		arg.Delta,
		arg.BalanceBefore,
		arg.BalanceAfter,
		arg.ExpireAt,
	)
	return err
}

const insertAccountChange = `-- name: InsertAccountChange :exec
INSERT INTO account_change_log (txn_no, account_no, delta, balance_before, balance_after)
VALUES (
  $1::uuid,
  $2,
  $3,
  $4,
  $5
)
`

type InsertAccountChangeParams struct {
	TxnNo         pgtype.UUID
	AccountNo     string
	Delta         int64
	BalanceBefore int64
	BalanceAfter  int64
}

func (q *Queries) InsertAccountChange(ctx context.Context, arg InsertAccountChangeParams) error {
	_, err := q.db.Exec(ctx, insertAccountChange,
		arg.TxnNo,
		arg.AccountNo,
		arg.Delta,
		arg.BalanceBefore,
		arg.BalanceAfter,
	)
	return err
}

const insertMerchantSecretCredential = `-- name: InsertMerchantSecretCredential :exec
INSERT INTO merchant_api_credential (
  merchant_no, secret_ciphertext, secret_version, active, created_at, updated_at
) VALUES (
  $1,
  $2,
  $3,
  true,
  NOW(),
  NOW()
)
`

type InsertMerchantSecretCredentialParams struct {
	MerchantNo       string
	SecretCiphertext string
	SecretVersion    int32
}

func (q *Queries) InsertMerchantSecretCredential(ctx context.Context, arg InsertMerchantSecretCredentialParams) error {
	_, err := q.db.Exec(ctx, insertMerchantSecretCredential, arg.MerchantNo, arg.SecretCiphertext, arg.SecretVersion)
	return err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_event (
  event_id, txn_no, merchant_no, out_trade_no, status, retry_count, next_retry_at, created_at, updated_at
) SELECT
  $1::uuid,
  $2::uuid,
  $3,
  NULLIF($4, ''),
  $5,
  0,
  NULL,
  NOW(),
  NOW()
WHERE EXISTS (
  SELECT 1
  FROM webhook_config wc
  WHERE wc.merchant_no = $6
    AND wc.enabled = TRUE
    AND BTRIM(wc.url) <> ''
)
ON CONFLICT DO NOTHING
`

type InsertOutboxEventParams struct {
	EventID           pgtype.UUID
	TxnNo             pgtype.UUID
	MerchantNo        string
	OutTradeNo        interface{}
	Status            string
	WebhookMerchantNo string
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.EventID,
		arg.TxnNo,
		arg.MerchantNo,
		arg.OutTradeNo,
		arg.Status,
		arg.WebhookMerchantNo,
	)
	return err
}

const leaseCodeRange = `-- name: LeaseCodeRange :one
UPDATE code_sequence
SET next_value = next_value + $1,
    updated_at = NOW()
WHERE code_type = $2
  AND scope_key = $3
RETURNING
  (next_value - $1)::bigint AS start_value,
  (next_value - 1)::bigint AS end_value
`

type LeaseCodeRangeParams struct {
	BatchSize int64
	CodeType  string
	ScopeKey  string
}

type LeaseCodeRangeRow struct {
	StartValue int64
	EndValue   int64
}

func (q *Queries) LeaseCodeRange(ctx context.Context, arg LeaseCodeRangeParams) (LeaseCodeRangeRow, error) {
	row := q.db.QueryRow(ctx, leaseCodeRange, arg.BatchSize, arg.CodeType, arg.ScopeKey)
	var i LeaseCodeRangeRow
	err := row.Scan(&i.StartValue, &i.EndValue)
	return i, err
}

const listAccountChangeLogs = `-- name: ListAccountChangeLogs :many
SELECT
  acl.change_id,
  acl.txn_no::text AS txn_no,
  acl.account_no,
  acl.delta,
  acl.balance_before,
  acl.balance_after,
  COALESCE(t.title, '') AS title,
  COALESCE(t.remark, '') AS remark,
  acl.created_at
FROM account_change_log acl
JOIN account a
  ON a.account_no = acl.account_no
LEFT JOIN txn t
  ON t.txn_no = acl.txn_no
WHERE a.merchant_no = $1
  AND acl.account_no = $2
  AND (
    NOT $3::bool
    OR (
      acl.created_at < $4::timestamptz
      OR (acl.created_at = $4::timestamptz AND acl.change_id < $5)
    )
  )
ORDER BY acl.created_at DESC, acl.change_id DESC
LIMIT $6
`

type ListAccountChangeLogsParams struct {
	MerchantNo      string
	AccountNo       string
	HasCursor       bool
	CursorCreatedAt pgtype.Timestamptz
	CursorChangeID  int64
	PageLimit       int32
}

type ListAccountChangeLogsRow struct {
	ChangeID      int64
	TxnNo         string
	AccountNo     string
	Delta         int64
	BalanceBefore int64
	BalanceAfter  int64
	Title         string
	Remark        string
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) ListAccountChangeLogs(ctx context.Context, arg ListAccountChangeLogsParams) ([]ListAccountChangeLogsRow, error) {
	rows, err := q.db.Query(ctx, listAccountChangeLogs,
		arg.MerchantNo,
		arg.AccountNo,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorChangeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountChangeLogsRow
	for rows.Next() {
		var i ListAccountChangeLogsRow
		if err := rows.Scan(
			&i.ChangeID,
			&i.TxnNo,
			&i.AccountNo,
			&i.Delta,
			&i.BalanceBefore,
			&i.BalanceAfter,
			&i.Title,
			&i.Remark,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailableAccountBooksForUpdate = `-- name: ListAvailableAccountBooksForUpdate :many
SELECT
  b.book_no,
  b.account_no,
  b.expire_at,
  b.balance
FROM account_book b
WHERE b.account_no = $1
  AND (
    (b.expire_at > $2::date AND b.balance > 0)
    OR b.expire_at = $3::date
  )
ORDER BY
  CASE WHEN b.expire_at = $3::date THEN 1 ELSE 0 END ASC,
  b.expire_at ASC,
  b.book_no ASC
FOR UPDATE OF b
`

type ListAvailableAccountBooksForUpdateParams struct {
	AccountNo  string
	NowUtc     pgtype.Date
	NoExpireAt pgtype.Date
}

type ListAvailableAccountBooksForUpdateRow struct {
	BookNo    pgtype.UUID
	AccountNo string
	ExpireAt  pgtype.Date
	Balance   int64
}

func (q *Queries) ListAvailableAccountBooksForUpdate(ctx context.Context, arg ListAvailableAccountBooksForUpdateParams) ([]ListAvailableAccountBooksForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listAvailableAccountBooksForUpdate, arg.AccountNo, arg.NowUtc, arg.NoExpireAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailableAccountBooksForUpdateRow
	for rows.Next() {
		var i ListAvailableAccountBooksForUpdateRow
		if err := rows.Scan(
			&i.BookNo,
			&i.AccountNo,
			&i.ExpireAt,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOriginDebitBookChanges = `-- name: ListOriginDebitBookChanges :many
SELECT
  delta,
  expire_at,
  created_at
FROM account_book_change_log
WHERE txn_no = $1::uuid
  AND account_no = $2
  AND delta < 0
ORDER BY change_id ASC
`

type ListOriginDebitBookChangesParams struct {
	TxnNo     pgtype.UUID
	AccountNo string
}

type ListOriginDebitBookChangesRow struct {
	Delta     int64
	ExpireAt  pgtype.Date
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListOriginDebitBookChanges(ctx context.Context, arg ListOriginDebitBookChangesParams) ([]ListOriginDebitBookChangesRow, error) {
	rows, err := q.db.Query(ctx, listOriginDebitBookChanges, arg.TxnNo, arg.AccountNo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOriginDebitBookChangesRow
	for rows.Next() {
		var i ListOriginDebitBookChangesRow
		if err := rows.Scan(&i.Delta, &i.ExpireAt, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransferTxns = `-- name: ListTransferTxns :many
SELECT
  t.txn_no::text AS txn_no,
  t.merchant_no,
  t.out_trade_no,
  COALESCE(t.title, '') AS title,
  COALESCE(t.remark, '') AS remark,
  COALESCE(t.biz_type, '') AS biz_type,
  COALESCE(t.transfer_scene, '') AS transfer_scene,
  COALESCE(t.debit_account_no, '') AS debit_account_no,
  COALESCE(t.credit_account_no, '') AS credit_account_no,
  t.credit_expire_at,
  t.amount,
  COALESCE(t.refund_of_txn_no::text, '')::text AS refund_of_txn_no,
  t.refundable_amount,
  COALESCE(t.status, '') AS status,
  COALESCE(t.error_code, '') AS error_code,
  COALESCE(t.error_msg, '') AS error_msg,
  t.created_at
FROM txn t
WHERE ($1::text = '' OR t.merchant_no = $1::text)
  AND (
    NOT $2::bool
    OR EXISTS (
      SELECT 1
      FROM account a
      JOIN customer c
        ON c.customer_no = a.customer_no
       AND c.merchant_no = t.merchant_no
      WHERE c.out_user_id = $3
        AND (
          a.account_no = t.debit_account_no
          OR a.account_no = t.credit_account_no
        )
    )
  )
  AND (NOT $4::bool OR t.transfer_scene = $5)
  AND (NOT $6::bool OR t.status = $7)
  AND (NOT $8::bool OR t.created_at >= $9::timestamptz)
  AND (NOT $10::bool OR t.created_at <= $11::timestamptz)
  AND (
    NOT $12::bool
    OR (
      t.created_at < $13::timestamptz
      OR (t.created_at = $13::timestamptz AND t.txn_no < $14)
    )
  )
ORDER BY t.created_at DESC, t.txn_no DESC
LIMIT $15
`

type ListTransferTxnsParams struct {
	MerchantNo      string
	HasOutUserID    bool
	OutUserID       string
	HasScene        bool
	Scene           pgtype.Text
	HasStatus       bool
	Status          string
	HasStartTime    bool
	StartTime       pgtype.Timestamptz
	HasEndTime      bool
	EndTime         pgtype.Timestamptz
	HasCursor       bool
	CursorCreatedAt pgtype.Timestamptz
	CursorTxnNo     pgtype.UUID
	PageLimit       int32
}

type ListTransferTxnsRow struct {
	TxnNo            string
	MerchantNo       string
	OutTradeNo       string
	Title            string
	Remark           string
	BizType          string
	TransferScene    string
	DebitAccountNo   string
	CreditAccountNo  string
	CreditExpireAt   pgtype.Date
	Amount           int64
	RefundOfTxnNo    string
	RefundableAmount int64
	Status           string
	ErrorCode        string
	ErrorMsg         string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) ListTransferTxns(ctx context.Context, arg ListTransferTxnsParams) ([]ListTransferTxnsRow, error) {
	rows, err := q.db.Query(ctx, listTransferTxns,
		arg.MerchantNo,
		arg.HasOutUserID,
		arg.OutUserID,
		arg.HasScene,
		arg.Scene,
		arg.HasStatus,
		arg.Status,
		arg.HasStartTime,
		arg.StartTime,
		arg.HasEndTime,
		arg.EndTime,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorTxnNo,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransferTxnsRow
	for rows.Next() {
		var i ListTransferTxnsRow
		if err := rows.Scan(
			&i.TxnNo,
			&i.MerchantNo,
			&i.OutTradeNo,
			&i.Title,
			&i.Remark,
			&i.BizType,
			&i.TransferScene,
			&i.DebitAccountNo,
			&i.CreditAccountNo,
			&i.CreditExpireAt,
			&i.Amount,
			&i.RefundOfTxnNo,
			&i.RefundableAmount,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorMsg,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransferTxnsByStatus = `-- name: ListTransferTxnsByStatus :many
SELECT
  t.txn_no::text AS txn_no,
  t.merchant_no,
  t.out_trade_no,
  COALESCE(t.title, '') AS title,
  COALESCE(t.remark, '') AS remark,
  COALESCE(t.biz_type, '') AS biz_type,
  COALESCE(t.transfer_scene, '') AS transfer_scene,
  COALESCE(t.debit_account_no, '') AS debit_account_no,
  COALESCE(t.credit_account_no, '') AS credit_account_no,
  t.credit_expire_at,
  t.amount,
  COALESCE(t.refund_of_txn_no::text, '')::text AS refund_of_txn_no,
  t.refundable_amount,
  COALESCE(t.status, '') AS status,
  COALESCE(t.error_code, '') AS error_code,
  COALESCE(t.error_msg, '') AS error_msg,
  t.created_at
FROM txn t
WHERE t.status = $1
ORDER BY t.updated_at ASC, t.txn_no ASC
LIMIT $2
`

type ListTransferTxnsByStatusParams struct {
	Status    string
	PageLimit int32
}

type ListTransferTxnsByStatusRow struct {
	TxnNo            string
	MerchantNo       string
	OutTradeNo       string
	Title            string
	Remark           string
	BizType          string
	TransferScene    string
	DebitAccountNo   string
	CreditAccountNo  string
	CreditExpireAt   pgtype.Date
	Amount           int64
	RefundOfTxnNo    string
	RefundableAmount int64
	Status           string
	ErrorCode        string
	ErrorMsg         string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) ListTransferTxnsByStatus(ctx context.Context, arg ListTransferTxnsByStatusParams) ([]ListTransferTxnsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listTransferTxnsByStatus, arg.Status, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransferTxnsByStatusRow
	for rows.Next() {
		var i ListTransferTxnsByStatusRow
		if err := rows.Scan(
			&i.TxnNo,
			&i.MerchantNo,
			&i.OutTradeNo,
			&i.Title,
			&i.Remark,
			&i.BizType,
			&i.TransferScene,
			&i.DebitAccountNo,
			&i.CreditAccountNo,
			&i.CreditExpireAt,
			&i.Amount,
			&i.RefundOfTxnNo,
			&i.RefundableAmount,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorMsg,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMerchantNoForUpdate = `-- name: LockMerchantNoForUpdate :one
SELECT merchant_no
FROM merchant
WHERE merchant_no = $1
FOR UPDATE
LIMIT 1
`

func (q *Queries) LockMerchantNoForUpdate(ctx context.Context, merchantNo string) (string, error) {
	row := q.db.QueryRow(ctx, lockMerchantNoForUpdate, merchantNo)
	var merchant_no string
	err := row.Scan(&merchant_no)
	return merchant_no, err
}

const markOutboxEventRetry = `-- name: MarkOutboxEventRetry :exec
UPDATE outbox_event
SET retry_count = $1,
    next_retry_at = $2::timestamptz,
    status = CASE WHEN $3::bool THEN 'DEAD' ELSE 'PENDING' END,
    updated_at = NOW()
WHERE event_id = NULLIF($4, '')::uuid
`

type MarkOutboxEventRetryParams struct {
	RetryCount  int32
	NextRetryAt pgtype.Timestamptz
	MarkDead    bool
	EventID     interface{}
}

func (q *Queries) MarkOutboxEventRetry(ctx context.Context, arg MarkOutboxEventRetryParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventRetry,
		arg.RetryCount,
		arg.NextRetryAt,
		arg.MarkDead,
		arg.EventID,
	)
	return err
}

const markOutboxEventSuccess = `-- name: MarkOutboxEventSuccess :exec
UPDATE outbox_event
SET status = 'SUCCESS',
    updated_at = NOW()
WHERE event_id = NULLIF($1, '')::uuid
`

func (q *Queries) MarkOutboxEventSuccess(ctx context.Context, eventID interface{}) error {
	_, err := q.db.Exec(ctx, markOutboxEventSuccess, eventID)
	return err
}

const setCustomerDefaultAccountIfEmpty = `-- name: SetCustomerDefaultAccountIfEmpty :execrows
UPDATE customer c
SET default_account_no = $1,
    updated_at = NOW()
WHERE c.merchant_no = $2
  AND c.customer_no = $3
  AND c.default_account_no IS NULL
  AND EXISTS (
    SELECT 1
    FROM account a
    WHERE a.account_no = $1
      AND a.merchant_no = c.merchant_no
      AND a.customer_no = c.customer_no
  )
`

type SetCustomerDefaultAccountIfEmptyParams struct {
	DefaultAccountNo pgtype.Text
	MerchantNo       string
	CustomerNo       string
}

func (q *Queries) SetCustomerDefaultAccountIfEmpty(ctx context.Context, arg SetCustomerDefaultAccountIfEmptyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCustomerDefaultAccountIfEmpty, arg.DefaultAccountNo, arg.MerchantNo, arg.CustomerNo)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tryCreditAccountBalanceNonBookRefund = `-- name: TryCreditAccountBalanceNonBookRefund :one
UPDATE account a
SET balance = a.balance + $1,
    updated_at = NOW()
WHERE a.account_no = $2
  AND a.book_enabled = false
RETURNING
  a.account_no,
  a.balance
`

type TryCreditAccountBalanceNonBookRefundParams struct {
	Amount    int64
	AccountNo string
}

type TryCreditAccountBalanceNonBookRefundRow struct {
	AccountNo string
	Balance   int64
}

func (q *Queries) TryCreditAccountBalanceNonBookRefund(ctx context.Context, arg TryCreditAccountBalanceNonBookRefundParams) (TryCreditAccountBalanceNonBookRefundRow, error) {
	row := q.db.QueryRow(ctx, tryCreditAccountBalanceNonBookRefund, arg.Amount, arg.AccountNo)
	var i TryCreditAccountBalanceNonBookRefundRow
	err := row.Scan(&i.AccountNo, &i.Balance)
	return i, err
}

const tryDecreaseTxnRefundable = `-- name: TryDecreaseTxnRefundable :one
UPDATE txn
SET refundable_amount = refundable_amount - $1,
    updated_at = NOW()
WHERE txn_no = NULLIF($2, '')::uuid
  AND refundable_amount >= $1
RETURNING refundable_amount
`

type TryDecreaseTxnRefundableParams struct {
	Amount int64
	TxnNo  interface{}
}

func (q *Queries) TryDecreaseTxnRefundable(ctx context.Context, arg TryDecreaseTxnRefundableParams) (int64, error) {
	row := q.db.QueryRow(ctx, tryDecreaseTxnRefundable, arg.Amount, arg.TxnNo)
	var refundable_amount int64
	err := row.Scan(&refundable_amount)
	return refundable_amount, err
}

const txnCount = `-- name: TxnCount :one
SELECT COUNT(*)::bigint AS txn_count
FROM txn
`

func (q *Queries) TxnCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, txnCount)
	var txn_count int64
	err := row.Scan(&txn_count)
	return txn_count, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE account
SET balance = $1,
    updated_at = NOW()
WHERE account_no = $2
`

type UpdateAccountBalanceParams struct {
	Balance   int64
	AccountNo string
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, arg.Balance, arg.AccountNo)
	return err
}

const updateAccountCapabilities = `-- name: UpdateAccountCapabilities :exec
UPDATE account
SET allow_debit_out = $1,
    allow_credit_in = $2,
    allow_transfer = $3,
    updated_at = NOW()
WHERE account_no = $4
`

type UpdateAccountCapabilitiesParams struct {
	AllowDebitOut bool
	AllowCreditIn bool
	AllowTransfer bool
	AccountNo     string
}

func (q *Queries) UpdateAccountCapabilities(ctx context.Context, arg UpdateAccountCapabilitiesParams) error {
	_, err := q.db.Exec(ctx, updateAccountCapabilities,
		arg.AllowDebitOut,
		arg.AllowCreditIn,
		arg.AllowTransfer,
		arg.AccountNo,
	)
	return err
}

const updateTransferTxnParties = `-- name: UpdateTransferTxnParties :exec
UPDATE txn
SET debit_account_no = $1,
    credit_account_no = $2,
    updated_at = NOW()
WHERE txn_no = NULLIF($3, '')::uuid
`

type UpdateTransferTxnPartiesParams struct {
	DebitAccountNo  pgtype.Text
	CreditAccountNo pgtype.Text
	TxnNo           interface{}
}

func (q *Queries) UpdateTransferTxnParties(ctx context.Context, arg UpdateTransferTxnPartiesParams) error {
	_, err := q.db.Exec(ctx, updateTransferTxnParties, arg.DebitAccountNo, arg.CreditAccountNo, arg.TxnNo)
	return err
}

const updateTransferTxnStatus = `-- name: UpdateTransferTxnStatus :exec
UPDATE txn
SET status = $1,
    error_code = NULLIF($2, ''),
    error_msg = NULLIF($3, ''),
    updated_at = NOW()
WHERE txn_no = NULLIF($4, '')::uuid
`

type UpdateTransferTxnStatusParams struct {
	Status    string
	ErrorCode interface{}
	ErrorMsg  interface{}
	TxnNo     interface{}
}

func (q *Queries) UpdateTransferTxnStatus(ctx context.Context, arg UpdateTransferTxnStatusParams) error {
	_, err := q.db.Exec(ctx, updateTransferTxnStatus,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMsg,
		arg.TxnNo,
	)
	return err
}

const updateTransferTxnStatusFrom = `-- name: UpdateTransferTxnStatusFrom :execrows
UPDATE txn
SET status = $1,
    error_code = NULLIF($2, ''),
    error_msg = NULLIF($3, ''),
    updated_at = NOW()
WHERE txn_no = NULLIF($4, '')::uuid
  AND status = $5
`

type UpdateTransferTxnStatusFromParams struct {
	NextStatus string
	ErrorCode  interface{}
	ErrorMsg   interface{}
	TxnNo      interface{}
	FromStatus string
}

func (q *Queries) UpdateTransferTxnStatusFrom(ctx context.Context, arg UpdateTransferTxnStatusFromParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTransferTxnStatusFrom,
		arg.NextStatus,
		arg.ErrorCode,
		arg.ErrorMsg,
		arg.TxnNo,
		arg.FromStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAccountBookBalance = `-- name: UpsertAccountBookBalance :one
INSERT INTO account_book (book_no, account_no, expire_at, balance)
VALUES (
  NULLIF($1, '')::uuid,
  $2,
  $3::date,
  $4
)
ON CONFLICT (account_no, expire_at)
DO UPDATE SET balance = account_book.balance + EXCLUDED.balance
RETURNING book_no, account_no, expire_at, balance
`

type UpsertAccountBookBalanceParams struct {
	BookNo    interface{}
	AccountNo string
	ExpireAt  pgtype.Date
	Delta     int64
}

type UpsertAccountBookBalanceRow struct {
	BookNo    pgtype.UUID
	AccountNo string
	ExpireAt  pgtype.Date
	Balance   int64
}

func (q *Queries) UpsertAccountBookBalance(ctx context.Context, arg UpsertAccountBookBalanceParams) (UpsertAccountBookBalanceRow, error) {
	row := q.db.QueryRow(ctx, upsertAccountBookBalance,
		arg.BookNo,
		arg.AccountNo,
		arg.ExpireAt,
		arg.Delta,
	)
	var i UpsertAccountBookBalanceRow
	err := row.Scan(
		&i.BookNo,
		&i.AccountNo,
		&i.ExpireAt,
		&i.Balance,
	)
	return i, err
}

const upsertWebhookConfig = `-- name: UpsertWebhookConfig :exec
INSERT INTO webhook_config (merchant_no, url, enabled, created_at, updated_at)
VALUES (
  $1,
  $2,
  $3,
  NOW(),
  NOW()
)
ON CONFLICT (merchant_no)
DO UPDATE SET
  url = EXCLUDED.url,
  enabled = EXCLUDED.enabled,
  updated_at = NOW()
`

type UpsertWebhookConfigParams struct {
	MerchantNo string
	Url        string
	Enabled    bool
}

func (q *Queries) UpsertWebhookConfig(ctx context.Context, arg UpsertWebhookConfigParams) error {
	_, err := q.db.Exec(ctx, upsertWebhookConfig, arg.MerchantNo, arg.Url, arg.Enabled)
	return err
}
