CREATE TABLE IF NOT EXISTS notify_log (
  notify_id BIGSERIAL PRIMARY KEY,
  txn_no UUID NOT NULL,
  status VARCHAR(16) NOT NULL,
  retries INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
